### ISSUE TITLE
Strict with nested commandDir not working

### ISSUE THREAD

**Issue by jwhitmarsh** [yargs/yargs#1353]
With nested commandDirs strict only works for top-level commands, and for unknown nested commands yargs just fails silently. After reading the tests, it looks like `strict()` defaults to be applied globally, but it just doesn't seem to work.

**Comment by bcoe** [comment]
@jwhitmarsh thanks for the bug report. If you do find the underlying cause would happily take a patch, otherwise labeling as high priority.

**Comment by mleguen** [comment]
@jwhitmarsh we fixed some issues with the way yargs works with subcommands in the latest release.

Could you please test your code with `npm i yargs@latest` to see if it is working now as expected?

If it is not the case, could you please give us an example of code reproducing the issue?

**Comment by mleguen** [comment]
I couldn't reproduce the issue with the following code:

```js
// index.js
const yargs = require('yargs')

console.log(
  yargs
    .strict()
    .commandDir("cmd")
    .parse()
)

// cmd/cmd1.js
module.exports = {
  command: "cmd1",
  describe: "description for cmd1",
  builder: yargs => {
    yargs.commandDir("subcmd")
  } 
}

// cmd/subcmd/subcmd1.js
module.exports = {
  command: "subcmd1",
  describe: "description for subcmd1",
}
```

Yargs complains about an unknown nested subcommand, as expected:

```bash
$ node index.js cmd1 cmd2
index.js cmd1

description for cmd1

Commands:
  index.js cmd1 subcmd1  description for subcmd1

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Unknown argument: cmd2
```

**Comment by bcoe** [comment]
@jwhitmarsh could you perhaps try:

```
npm i yargs@next
```

And see if this is continuing to cause issues for you?

**Comment by jwhitmarsh** [comment]
Apologies all, I had a busy September. The fix looks to have solved the issue where non demanded arguments weren't being reported as errors, but i'm still getting a silent fail for using an unrecognised nested command. This occurs even if I add `strict()` to each of my nested command builders. 

```js
// "foo" does not expect an argument, this throws an error as expected
cli foo -a
```

```js
// "bar" is not a top level command, this throws as expected
cli bar
```

```js
// "foo" is a top level command, but "sausage" isn't a nested command, 
// and this is failing saliently
cli foo sausage
```

**Comment by bcoe** [comment]
@jwhitmarsh mind opening a new issue, with this specific edge-case that's failing.

Hopefully we can address it soon.

**Comment by WestonThayer** [comment]
The [advanced.md](https://github.com/yargs/yargs/blob/561fc7a787228b226e0ba76ab674456cbd30cd37/docs/advanced.md#example-command-hierarchy-using-commanddir) doc sets you up to hit this scenario. Modifying @mleguen's code...

```js
// index.js
const yargs = require('yargs')

console.log(
  yargs
    .strict()
    .commandDir("cmd")
    .parse()
)

// cmd/cmd1.js
module.exports = {
  command: "cmd1 <subcmd>", // <<<<<<<<< adding <subcmd> means strict() no longer applies
  describe: "description for cmd1",
  builder: yargs => {
    yargs.commandDir("subcmd")
  } 
}

// cmd/subcmd/subcmd1.js
module.exports = {
  command: "subcmd1",
  describe: "description for subcmd1",
}
```

`node index.js cmd1 cmd2` silently fails. `cmd1.js`'s `exports.handler` would be called with `argv.cmd2 === true`, so you could do your strict validation there.

I can see arguments for an against this behavior, just putting a note here in case anyone else lands on this issue. FWIW, having to omit `<subcmd>` for `.strict()` to work makes `node index.js --help` confusing, since there's no clue that `cmd1` has subcommands.
